cart/urls.py
from . import views
from django.urls import path

app_name='cart'
urlpatterns = [
    path('add/<int:product_id>/',views.add_cart,name="add_cart"),
    path('cart_details',views.cart_details,name="cart_details"),
    path('remove/<int:product_id>/',views.cart_remove,name="cart_remove"),
    path('full_remove/<int:product_id>/', views.full_remove, name="full_remove"),

]

ecommerceapp/urls.py
from . import views
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static

app_name='ecommerceapp'
urlpatterns = [
    path('login/',views.allProdCat,name='allProdCat'),
    path('<slug:c_slug>/',views.allProdCat,name='products_by_category'),
    path('<slug:c_slug>/<slug:product_slug>/',views.ProdCatDetail,name='ProdCatDetail'),
    path('register/r',views.register,name='register'),
    path('',views.login,name='login'),
    path('logout',views.logout,name='logout'),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

ecommerceproject/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('ecommerceapp.urls')),
    path('search/',include('search_app.urls')),
    path('cart/', include('cart.urls')),
]

search_app/urls.py
from . import views
from django.urls import path

app_name="search_app"

urlpatterns=[
    path('search',views.search_res,name='search_res'),
]

cart/models.py
from django.db import models
from ecommerceapp.models import Product
# Create your models here.

class Cart(models.Model):
    cart_id=models.CharField(max_length=250,blank=True)
    date_added=models.DateField(auto_now_add=True)
    username = models.CharField(max_length=250, blank=True)

    class Meta:
        db_table='Cart'
        ordering=['date_added']
        def __str__(self):
            return self.cart_id

class CartItem(models.Model):
    product=models.ForeignKey(Product,on_delete=models.CASCADE)
    cart=models.ForeignKey(Cart,on_delete=models.CASCADE)
    quantity=models.IntegerField()
    active=models.BooleanField(default=True)
    username = models.CharField(max_length=250, blank=True)

    class Meta:
        db_table='CartItem'

    def sub_total(self):
        return self.product.price*self.quantity

    def __str__(self):
        return self.product

cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from ecommerceapp.models import Product
from .models import Cart, CartItem
from django.core.exceptions import ObjectDoesNotExist


# Create your views here.

def _cart_id(request):
    cart = request.session.session_key
    if not cart:
        cart = request.session.create()
    return cart

def add_cart(request, product_id):
    ok1=request.session['username']
    product = Product.objects.get(id=product_id)
    try:
        cart = Cart.objects.get(cart_id=_cart_id(request),username=ok1)
    except Cart.DoesNotExist:
        cart = Cart.objects.create(cart_id=_cart_id(request),username=ok1)
        cart.save()
    try:
        cart_item = CartItem.objects.get(product=product, cart=cart,username=ok1)
        if cart_item.quantity < cart_item.product.stock:
            cart_item.quantity += 1 
        cart_item.save()
    except CartItem.DoesNotExist:
        cart_item = CartItem.objects.create(product=product, quantity=1, cart=cart,username=ok1)
        cart_item.save()
    return redirect('cart:cart_details')


def cart_details(request, total=0, counter=0, cart_items=None):
    ok1 = request.session['username']
    try:
        cart = Cart.objects.get(cart_id=_cart_id(request),username=ok1)
        cart_items = CartItem.objects.filter(cart=cart, active=True,username=ok1)
        for cart_item in cart_items:
            total += (cart_item.product.price * cart_item.quantity)
            counter = cart_item.quantity
    except ObjectDoesNotExist:
        pass
    return render(request,'cart.html',dict(cart_items=cart_items, counter=counter, total=total))

def cart_remove(request,product_id):
    ok1 = request.session['username']
    cart=Cart.objects.get(cart_id=_cart_id(request),username=ok1)
    product=get_object_or_404(Product,id=product_id)
    cart_item=CartItem.objects.get(product=product,cart=cart,username=ok1)
    if cart_item.quantity > 1:
        cart_item.quantity -=1
        cart_item.save()
    else:
        cart_item.delete()
    return redirect('cart:cart_details')



def full_remove(request,product_id):
    ok1 = request.session['username']
    cart=Cart.objects.get(cart_id=_cart_id(request),username=ok1)
    product=get_object_or_404(Product,id=product_id)
    cart_item=CartItem.objects.get(product=product,cart=cart,username=ok1)
    cart_item.delete()
    return redirect('cart:cart_details')

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link href="https://fonts.googleapis.com/css2?family=Libre+Baskerville:ital@1&display=swap" rel="stylesheet">
    <meta name="description" content="{% block metsdescription %} {% endblock %}">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/custom.css' %}">
    <script src="https://kit.fontawesome.com/a076d05399.js"></script>
</head>
<body>
<div>
    {% include 'header.html' %}
    {% include 'navbar.html' %}
    {% block content %}
    {% endblock %}
</div>
{% include 'footer.html' %}
<script src="{% static 'js/jquery-3.2.1.slim.min.js' %}"></script>
<script src="{% static 'js/popper.min.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>

</body>
</html>

templates/cart.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}
        Welocme to the cart you can have anything here
{% endblock %}
{% block title %}
 Cart- shop your favourite !!!
{% endblock %}
{% block content %}
{% if not cart_items %}
<div>
    <div class="text-center">
        <br>
        <h1 class="text-center my_title">
            Your shopping cart is empty
        </h1>
        <br>
        <p class="text-center">
            Please click <a href="{% url 'ecommerceapp:allProdCat' %}">Here</a>
        </p>
    </div>
</div>
{% else %}
<div>
    <div class="text=center">
        <br>
        <h1 class="text-center my_title">
            Your shopping cart
        </h1>
        <br>
    </div>
</div>
<div class="row mx-auto">
    <div class="col-12 col-sm-12 col-md-12 col-lg-6 text-center">
        <table class="table my_custom_table">
            <thead class="my_custom_thead">
                <tr>
                    <th colspan="5">Your Items</th>
                </tr>
            </thead>
            <tbody class="">
            {% for cart_item in cart_items %}
            <tr>
                <td>
                    <a href="cart_item.product.get_absolute_url"><img src={{cart_item.product.img.url}} class="float-left rounded custom_image" height="70" width="70"></a>
                </td>
                <td class="text-left">
                    {{cart_item.product.name}}
                    <br>
                    Unit price:{{cart_item.product.price}}
                    <br>
                    Quantity:{{cart_item.quantity}} × ₹{{cart_item.product.price}}
                </td>
                <td>₹{{cart_item.sub_total}}</td>
                {% if cart_item.quantity < cart_item.product.stock %}
                <td>
                    <a href="{% url 'cart:add_cart' cart_item.product.id %}" class="custom_a"><i class="far fa-plus-square custom_icon"></i></a>&nbsp;
                    <a href="{% url 'cart:cart_remove' cart_item.product.id %}" class="custom_icon"><i class="far fa-minus-square custom_icon"></i></a>&nbsp;<a href="{% url 'cart:full_remove' cart_item.product.id %}" class="custom_icon"><i class="far fa-trash-alt custom_icon"></i></a>
                </td>
                {% else %}
                <td>
                    <a href="{% url 'cart:cart_remove' cart_item.product.id %}" class="custom_icon"><i class="far fa-minus-square custom_icon"></i></a>&nbsp;<a href="{% url 'cart:full_remove' cart_item.product.id %}" class="custom_icon"><i class="far fa-trash-alt custom_icon"></i></a>
                </td>
                {% endif %}
            </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
    <div class="col-12 col-sm-12 col-md-12 col-lg-6 text-center">
        <table class="table my_custom_table">
            <thead class="my_custon_thead">
                <tr>
                    <th>Checkout</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td>Please review your shopping cart items before proceding with the payment</td>
                </tr>
                <tr>
                    <td>
                        <strong>₹ {{ total }}</strong>
                    </td>
                </tr>
            </tbody>
        </table>
        <div class="mx-auto">
            <a href="{% url 'ecommerceapp:allProdCat' %}" class="btn btn-secondary btn-block my_custom_button">Continue Your Shopping</a>
        </div>
    </div>
</div><br>
{% endif %}
{% endblock %}

templates/category.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}
    {% if category  %}
        {{category.desc |truncatewords:155 }}
    {% else %}
        Welocme to the cart you can have anything here
    {% endif %}
{% endblock %}
{% block title %}
    {% if category %}
        {{category.name}}-Shop cart
    {% else %}
        See our collections here -Shop cart
    {% endif %}
{% endblock %}
{% block content %}
    {% if category %}
        <div class="row my_row_class">
            <div class="mx-auto">
                <p><a href="{% url 'ecommerceapp:allProdCat' %}">Our product collection</a><{{category.name}}/p>
            </div>
        </div>
    {% endif %}
<div div="mx-auto">
    {% if category %}
        <center><img src="{{category.img.url}}" alt="{{category.name}}" width="350" height="350"></center>
</div><br>
<div>
    <h1 class="text-center my_title">{{category.name}}</h1><br>
    <p class="text-justify">{{category.desc}}</p>
</div>
    {% else %}
        <div>
            <img src="{% static 'img/Shopping Cart.png' %}" width="1350" height="350" alt="" >
        </div>
<br>
<div>
    <h1>Our product collections</h1>
    <p>Lorem ipsum, or lipsum as it is sometimes known, is dummy text used in laying out print, graphic or web designs. The passage is attributed to an unknown typesetter in the 15th century who is thought to have scrambled parts of Cicero's De Finibus Bonorum et Malorum for use in a type specimen book.</p>
</div>
    {% endif %}
<div class="container">
    <div class="row max-auto">
        {% for product in products.object_list %}
        <div class="my_bottom_margin col-09 col-sm-12 col-md-4 col-lg-4">
            <div class="card text-center" style="width: 18rem;">
                <a href="{{product.get_url}}"><img class="car-img-top my_imgs" src="{{product.img.url}}" alt="{{product.name}}" style="width:250px; height:300px; padding-top:6px;"> </a>
                <div class="card-body">
                    <h4>{{product.name}}</h4>
                    <h4>₹{{product.price}}</h4>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
    <div class="mx-auto">
        <div class="text-center">
        {% for pg in products.paginator.page_range %}
        <a href="?page={{pg}}" class="btn btn-light btn-sm {% if products.number == pg %}active{% endif %}">{{pg}}</a>{% endfor %}
        </div>
    </div>
</div>
{% endblock %}

templates/footer.html
<div class="footer navbar-fixed-bottom my_footer">
    <p class="text-center">&copy; Sujin's creations. All rights go to sujin.</p>
</div>

templates/header.html
{% load static %}
<div>
    <center>
        <img src="{% static 'img/online shopping center.png' %}" alt="This is the logo">
    </center>
</div>

templates/login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>LOGIN</title>
    <link rel="stylesheet" href="{% static 'css/login.css' %}">
</head>
<body>
<div class='bold-line'></div>
<div class='container'>
  <div class='window'>
    <div class='overlay'></div>
    <div class='content'>
      <div class='welcome'>Hello There!</div>
      <div class='subtitle'>Create an account if you are new here.</div>
        <form method="post">
            {% csrf_token %}
      <div class='input-fields'>
        <input type='text' placeholder='Username' class='input-line full-width' name="username">
        <input type='password' placeholder='Password' class='input-line full-width' name="password">

      </div>
            <div><input type="submit" class='ghost-round full-width' value="LOGIN"></div>
            </form>

        <div class='spacing'><a href="register/r">or create account here</a></div>
    </div>
  </div>
</div>
</body>
</html>

templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <h3 class="navbar-brand">Shopping Center</h3>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
{% if user.is_authenticated %}
      <li class="nav-item">

        <h5 class="navbar-brand">{{user.username}}</h5>
      </li>
    {% endif %}
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="/login/">Home <span class="sr-only">(current)</span></a>
      </li>

      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Categories
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="{% url 'ecommerceapp:allProdCat' %}">All Products</a>
          {% for cat in links %}
          <a class="dropdown-item" href="{{cat.get_url}}">{{cat.name}}</a>
          {% endfor %}
<!--          <div class="dropdown-divider"></div>-->
<!--          <a class="dropdown-item" href="#">Something else n.M</a>-->
<!--        </div>-->
        </div>
      </li>


    {% if item_count > 0 %}
      <li class="nav-item">
        <a class="nav-link" href="{% url 'cart:cart_details' %}"><i class="fas fa-cart-plus">{{item_count}}</i></a>
      </li>
    {% else %}
        <li class="nav-item">
        <a class="nav-link" href="{% url 'cart:cart_details' %}"><i class="fas fa-cart-plus"></i></a>
      </li>
    {% endif %}


  <li class="nav-item">
        <a class="nav-link disabled" href="/logout">Logout</a>
      </li>
    </ul>
    <form class="form-inline my-2 my-lg-0" action="{% url 'search_app:search_res' %}" method="get">
      {% csrf_token %}
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search" name="q">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit"><i class="fas fa-search"></i></button>
    </form>
  </div>
</nav>

<!--<nav>-->
<!--    <ul>-->
<!--        <li><a href="{% url 'ecommerceapp:allProdCat' %}">All Products</a></li>-->
<!--        <ul>-->
<!--        {% for cat in links %}-->
<!--            <li><a href="{{cat.get_url}}">{{cat.name}}</a> </li>-->
<!--        {% endfor %}-->
<!--        </ul>-->
<!--        <li>Your cart</li>-->
<!--    </ul>-->

<!--</nav>-->

templates/product.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}
    {{product.desc |truncatewords:150}}
{% endblock %}
{% block title %}
    {{product.name}}-Shopping Cart
{% endblock %}
{% block content %}
    <div class="row my_prod_row_class">
        <div class="mx-auto">
            <p><a href="{% url 'ecommerceapp:allProdCat' %}">Home</a> |<a href="{{product.category.get_url}}">{{product.name}}</a> </p>
        </div>
        <div class="container">
            <br>
            <div class="row">
                <div class="col-12 col-sm-12 col-md-12 col-lg-6 text-center">
                    <div style="min-width:18rem;">
                    <img src="{{product.img.url}}" alt="{{product.name}}">
                </div>
            </div>
            <div class="col-12 col-sm-12 col-md-12 col-lg-6">
                <div>
                    <h1 class="my_prod_title">{{product.name}}</h1>
                    <p>₹{{product.price}}</p>
                    <p class="my_title">Product Description</p>
                    <p class="text-justify my_prod_text">{{product.desc}}</p>
                    {% if product.stock <= 0 %}
                        <p class="text-justify my_prod_text"><b>OUT OF STOCK</b></p>
                    {% else %}
                        <a class="btn-secondary" href="{% url 'cart:add_cart' product.id %}">Add to cart</a>
                    {% endif %}

                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/registration.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Register</title>
    <link rel="stylesheet" href="{% static 'css/login.css' %}">
</head>
<body>
<div class='bold-line'></div>
<div class='container'>
  <div class='window'>
    <div class='overlay'></div>
    <div class='content'>
      <div class='welcome'>Hello There!</div>
      <div class='subtitle'>Create an account if you are new here.</div>
        <div class='subtitle'>
            {% for message in messages %}
            {{message}}
            {% endfor %}
        </div>
        <form method="post">
            {% csrf_token %}
      <div class='input-fields'>
          <input type='text' placeholder='Name' class='input-line full-width' name="first_name">
          <input type='text' placeholder='Username' class='input-line full-width' name="username">
          <input type='email' placeholder='Email ID' class='input-line full-width' name="email">
        <input type='password' placeholder='Password' class='input-line full-width' name="password1">
        <input type='password' placeholder='Confirm Password' class='input-line full-width' name="password2">

      </div>
            <div><input type="submit" class='ghost-round full-width' value="Register"></div>
            </form>
    </div>
  </div>
</div>
</body>
</html>

templates/search.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}
    {{product.desc |truncatewords:150}}
{% endblock %}
{% block title %}
    {{product.name}}-Shopping Cart
{% endblock %}
{% block content %}
<div>
<p class="text-center my_search_text">You have searched for {{query}}</p>
</div>
<div class="container">
    <div class="row max-auto">
        {% for product in products %}
        <div class="my_bottom_margin col-09 col-sm-12 col-md-4 col-lg-4">
            <div class="card text-center" style="width: 18rem;">
                <a href="{{product.get_url}}"><img class="car-img-top my_img" src="{{product.img.url}}" width="200" height="200" alt="{{product.name}}"> </a>
                <div class="card-body">
                    <h4>{{product.name}}</h4>
                    <h4>₹{{product.price}}</h4>
                </div>
            </div>
        </div>
        {% empty %}
        <div class="row mx-auto">
            <p class="text-center my_search_text">ZERO reults found</p>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}